version: "3.9"

services:
  users:
    build:
      context: ./users
    ports:
      - "5002:5002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  quotes:
    build:
      context: ./quotes
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  search:
    build:
      context: ./search
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1"]