apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search-api
        image: search-api:latest
        ports:
        - containerPort: 5000
