apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search-api
        image: amaury1305/search-api:latest
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: "redis-service"  # Le nom du service Redis que tu viens de créer
          - name: REDIS_PORT
            value: "6379"  # Le port de Redis
