apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-api
        image: amaury1305/users-api:latest
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: "redis-service"  # Le nom du service Redis que tu viens de créer
          - name: REDIS_PORT
            value: "6379"  # Le port de Redis
